version: '3'

services:
  gatling-spring-boot-example:
    container_name: "gatling-spring-boot-example"
    image: "postgres:10.6"
    restart: always
    ports:
      - "15432:5432"
    volumes:
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: spring-boot
      POSTGRES_DB: spring-boot
